services:
  telegram-bot:
    build: .
    container_name: innokentiy-bot
    restart: unless-stopped
    environment:
      # Telegram Bot
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      
      # Supabase (подключение к существующему Kong gateway)
      - SUPABASE_URL=http://supabase-kong:8000
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # N8N Webhooks (подключение к существующему N8N)
      - N8N_NICHE_WEBHOOK_URL=${N8N_NICHE_WEBHOOK_URL}
      - N8N_TOPIC_WEBHOOK_URL=${N8N_TOPIC_WEBHOOK_URL}
      - N8N_POST_WEBHOOK_URL=${N8N_POST_WEBHOOK_URL}
      
      # Admin Notifications
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - ENABLE_ADMIN_NOTIFICATIONS=${ENABLE_ADMIN_NOTIFICATIONS:-True}
      
      # Bot Configuration
      - MAX_USERS=${MAX_USERS:-1000}
      - DEBUG=${DEBUG:-True}
      
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    
    networks:
      - n8n_default
      - supabase_default
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  # Подключение к существующим сетям
  n8n_default:
    external: true
  supabase_default:
    external: true

volumes:
  bot-logs:
    driver: local
